# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-pitv"
BBFILE_PATTERN_meta-pitv = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-pitv = "26"
LAYERVERSION_meta-pitv = "1"
LAYERSERIES_COMPAT_meta-pitv = "wrynose"