require conf/distro/poky.conf

DISTRO_VERSION = "1.0"
DISTRO = "pitv"
DISTRO_NAME = "PiTv"

INIT_MANAGER = "systemd"

# Features not covered by the init-manager include
DISTRO_FEATURES:append = " pam"

LICENSE_FLAGS_ACCEPTED += "synaptics-killswitch"
